apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
    ver: 20210207_2100
spec:
  containers:
  - name: voting-app
    image: dockersamples/examplevotingapp_vote
    ports:
    - containerPort: 80
